In [ ]:
#This is pyenv file for anlyze data after download. I also used this for making yeary subset

In [1]:
import pandas as pd

In [4]:
import csv

In [7]:
df1 = pd.read_csv('FLAT_RCL_POST_2010.txt', sep='\t',quoting=csv.QUOTE_NONE,header=None,)

/var/folders/0r/j33d8qm5689bkc0t4q54h4880000gn/T/ipykernel_25182/3461798395.py:1: DtypeWarning: Columns (0: 17, 1: 18, 2: 24, 3: 25, 4: 26) have mixed types. Specify dtype option on import or set low_memory=False.
  df1 = pd.read_csv('FLAT_RCL_POST_2010.txt', sep='\t',quoting=csv.QUOTE_NONE,header=None,)

In [12]:
df1

,RECORD_ID,CAMPNO,MAKETXT,MODELTXT,YEARTXT,MFGCAMPNO,COMPNAME,MFGNAME,BGMAN,ENDMAN,...,DESC_DEFECT,CONEQUENCE_DEFECT,CORRECTIVE_ACTION,NOTES,RCL_CMPT_ID,MFR_COMP_NAME,MFR_COMP_DESC,MFR_COMP_PTNO,PARK_IT,PARK_OUTSIDE
0,81716,10V008000,DODGE,GRAND CARAVAN,2006,J38,AIR BAGS:FRONTAL:SENSOR/CONTROL MODULE-INACTIVE,CHRYSLER GROUP LLC,20050119.0,20060405.0,...,CHRYSLER IS RECALLING CERTAIN MODEL YEAR 2005-...,"IF THE FRONT CRASH SENSORS BECOME INOPERATIVE,...",CHRYSLER WILL REPLACE THE FRONT AIRBAG SENSORS...,CHRYSLER'S CAMPAIGN NUMBER IS J38. CHRYSLER HA...,34617000207915000000258,NaN,NaN,NaN,No,No
1,81717,10V317000,PIERCE,DASH,2006,39-0139830,"SERVICE BRAKES, HYDRAULIC:FOUNDATION COMPONENT...",PIERCE MANUFACTURING,NaN,NaN,...,PIERCE IS RECALLING CERTAIN MODEL YEAR 2006 TH...,"IF THIS INTERFERENCE OCCURS, BRAKING PERFORMAN...",DEALERS WILL INSTALL NEW AUTOMATIC TIRE CHAIN ...,PIERCE SAFETY RECALL NO. 39-0139830. OWNERS MA...,36361000876842000000080,NaN,NaN,NaN,No,No
2,81718,10V317000,PIERCE,DASH,2009,39-0139830,"SERVICE BRAKES, HYDRAULIC:FOUNDATION COMPONENT...",PIERCE MANUFACTURING,NaN,NaN,...,PIERCE IS RECALLING CERTAIN MODEL YEAR 2006 TH...,"IF THIS INTERFERENCE OCCURS, BRAKING PERFORMAN...",DEALERS WILL INSTALL NEW AUTOMATIC TIRE CHAIN ...,PIERCE SAFETY RECALL NO. 39-0139830. OWNERS MA...,36361000734769000000080,NaN,NaN,NaN,No,No
3,81719,10V317000,PIERCE,ARROW XT,2009,39-0139830,"SERVICE BRAKES, HYDRAULIC:FOUNDATION COMPONENT...",PIERCE MANUFACTURING,NaN,NaN,...,PIERCE IS RECALLING CERTAIN MODEL YEAR 2006 TH...,"IF THIS INTERFERENCE OCCURS, BRAKING PERFORMAN...",DEALERS WILL INSTALL NEW AUTOMATIC TIRE CHAIN ...,PIERCE SAFETY RECALL NO. 39-0139830. OWNERS MA...,36361000677768000000080,NaN,NaN,NaN,No,No
4,81720,10V317000,PIERCE,ARROW XT,2008,39-0139830,"SERVICE BRAKES, HYDRAULIC:FOUNDATION COMPONENT...",PIERCE MANUFACTURING,NaN,NaN,...,PIERCE IS RECALLING CERTAIN MODEL YEAR 2006 TH...,"IF THIS INTERFERENCE OCCURS, BRAKING PERFORMAN...",DEALERS WILL INSTALL NEW AUTOMATIC TIRE CHAIN ...,PIERCE SAFETY RECALL NO. 39-0139830. OWNERS MA...,36361000390634000000080,NaN,NaN,NaN,No,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
242464,324180,26V332000,HONDA,ACCORD,2020,Refer to Comments,AIR BAGS:SENSOR:OCCUPANT CLASSIFICATION:FRONT ...,Honda (American Honda Motor Co.),NaN,NaN,...,Honda (American Honda Motor Co.) is recalling ...,Air bags that deploy unintentionally during a ...,"Dealers will replace the seat weight sensors, ...",NaN,261316004288717000001831,"Sensor Assy, Weight","Sensor Assy, Weight",81168-T2F-L012-M1,No,No
242465,324181,26V332000,HONDA,ACCORD,2020,Refer to Comments,AIR BAGS:SENSOR:OCCUPANT CLASSIFICATION:FRONT ...,Honda (American Honda Motor Co.),NaN,NaN,...,Honda (American Honda Motor Co.) is recalling ...,Air bags that deploy unintentionally during a ...,"Dealers will replace the seat weight sensors, ...",NaN,261316004288717000001831,"Sensor Assy, Weight","Sensor Assy, Weight",81167-T2F-L012-M1,No,No
242466,324182,26V332000,HONDA,ACCORD,2021,Refer to Comments,AIR BAGS:SENSOR:OCCUPANT CLASSIFICATION:FRONT ...,Honda (American Honda Motor Co.),NaN,NaN,...,Honda (American Honda Motor Co.) is recalling ...,Air bags that deploy unintentionally during a ...,"Dealers will replace the seat weight sensors, ...",NaN,261316004697750000001831,"Sensor Assy, Weight","Sensor Assy, Weight",81168-T2F-L012-M1,No,No
242467,324183,26V332000,HONDA,ACCORD,2021,Refer to Comments,AIR BAGS:SENSOR:OCCUPANT CLASSIFICATION:FRONT ...,Honda (American Honda Motor Co.),NaN,NaN,...,Honda (American Honda Motor Co.) is recalling ...,Air bags that deploy unintentionally during a ...,"Dealers will replace the seat weight sensors, ...",NaN,261316004697750000001831,"Sensor Assy, Weight","Sensor Assy, Weight",81167-T2F-L012-M1,No,No
242468,324184,26V332000,HONDA,ACCORD,2022,Refer to Comments,AIR BAGS:SENSOR:OCCUPANT CLASSIFICATION:FRONT ...,Honda (American Honda Motor Co.),NaN,20221119.0,...,Honda (American Honda Motor Co.) is recalling ...,Air bags that deploy unintentionally during a ...,"Dealers will replace the seat weight sensors, ...",NaN,261316005001759000001831,"Sensor Assy, Weight","Sensor Assy, Weight",81168-T2F-L012-M1,No,No

In [11]:
df1.columns = [
    "RECORD_ID",
    "CAMPNO",
    "MAKETXT",
    "MODELTXT",
    "YEARTXT",
    "MFGCAMPNO",
    "COMPNAME",
    "MFGNAME",
    "BGMAN",
    "ENDMAN",
    "RCLTYPECD",
    "POTAFF",
    "ODATE",
    "INFLUENCED_BY",
    "MFGTXT",
    "RCDATE",
    "DATEA",
    "RPNO",
    "FMVSS",
    "DESC_DEFECT",
    "CONEQUENCE_DEFECT",
    "CORRECTIVE_ACTION",
    "NOTES",
    "RCL_CMPT_ID",
    "MFR_COMP_NAME",
    "MFR_COMP_DESC",
    "MFR_COMP_PTNO",
    "PARK_IT",
    "PARK_OUTSIDE"
]

In [13]:
df2 = pd.read_csv('FLAT_RCL_PRE_2010.txt', sep='\t',quoting=csv.QUOTE_NONE,header=None,)

In [14]:
df2.columns = [
    "RECORD_ID",
    "CAMPNO",
    "MAKETXT",
    "MODELTXT",
    "YEARTXT",
    "MFGCAMPNO",
    "COMPNAME",
    "MFGNAME",
    "BGMAN",
    "ENDMAN",
    "RCLTYPECD",
    "POTAFF",
    "ODATE",
    "INFLUENCED_BY",
    "MFGTXT",
    "RCDATE",
    "DATEA",
    "RPNO",
    "FMVSS",
    "DESC_DEFECT",
    "CONEQUENCE_DEFECT",
    "CORRECTIVE_ACTION",
    "NOTES",
    "RCL_CMPT_ID",
    "MFR_COMP_NAME",
    "MFR_COMP_DESC",
    "MFR_COMP_PTNO",
    "PARK_IT",
    "PARK_OUTSIDE"
]

In [15]:
df_connected= pd.concat([df1, df2])

In [17]:
print(df1.shape)
print(df2.shape)
print(df_connected.shape)

(242469, 29)
(81710, 29)
(324179, 29)

In [18]:
df_connected[["YEARTXT" ]] = df_connected[["YEARTXT"]].astype('int')

In [20]:
df_connected.value_counts('COMPNAME').head(10)

COMPNAME
ELECTRICAL SYSTEM:SOFTWARE                  20531
TIRES:MARKINGS                              19535
COMMUNICATION: AUTO CRASH NOTIFICATION      16688
EQUIPMENT                                   11927
FUEL SYSTEM, GASOLINE:DELIVERY:FUEL PUMP     9177
EQUIPMENT:RECREATIONAL VEHICLE/TRAILER       8348
BACK OVER PREVENTION:DISPLAY FUNCTION        7894
EQUIPMENT:OTHER:LABELS                       5803
EXTERIOR LIGHTING                            5235
EQUIPMENT ADAPTIVE/MOBILITY                  5217
Name: count, dtype: int64

In [22]:
df_connected[df_connected['YEARTXT']==2000].value_counts('COMPNAME').head(10)

COMPNAME
EQUIPMENT:RECREATIONAL VEHICLE/TRAILER    531
EXTERIOR LIGHTING                         164
SERVICE BRAKES, AIR:SUPPLY:CHECK VALVE    130
SEAT BELTS:FRONT:BUCKLE ASSEMBLY          129
EQUIPMENT                                 121
STEERING:LINKAGES:TIE ROD ASSEMBLY        110
EXTERIOR LIGHTING:HEADLIGHTS               94
EQUIPMENT:OTHER:LABELS                     89
SERVICE BRAKES, AIR:ANTILOCK               86
VEHICLE SPEED CONTROL                      64
Name: count, dtype: int64

In [29]:
df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2000)].value_counts('COMPNAME').head(10)

COMPNAME
EQUIPMENT:RECREATIONAL VEHICLE/TRAILER                     531
SERVICE BRAKES, AIR:SUPPLY:CHECK VALVE                     130
SEAT BELTS:FRONT:BUCKLE ASSEMBLY                           129
STEERING:LINKAGES:TIE ROD ASSEMBLY                         110
EQUIPMENT:OTHER:LABELS                                      89
SERVICE BRAKES, AIR:ANTILOCK                                86
EQUIPMENT                                                   79
VEHICLE SPEED CONTROL                                       64
SERVICE BRAKES, HYDRAULIC:BRAKE FLUID LOW WARNING: LAMP     62
AIR BAGS:FRONTAL:DRIVER SIDE:INFLATOR MODULE                58
Name: count, dtype: int64

In [31]:
df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2010)].value_counts('COMPNAME').head(10)

COMPNAME
EQUIPMENT                                          613
AIR BAGS:FRONTAL:PASSENGER SIDE:INFLATOR MODULE    611
EQUIPMENT ADAPTIVE/MOBILITY                        438
AIR BAGS:FRONTAL:DRIVER SIDE:INFLATOR MODULE       367
ELECTRICAL SYSTEM                                  229
AIR BAGS:FRONTAL                                   216
LATCHES/LOCKS/LINKAGES                             186
EQUIPMENT:OTHER:LABELS                             177
EQUIPMENT:RECREATIONAL VEHICLE/TRAILER             135
SEATS                                              134
Name: count, dtype: int64

In [33]:
df_connected[df_connected['YEARTXT']==2010].value_counts('COMPNAME').head(10)

COMPNAME
AIR BAGS:FRONTAL:PASSENGER SIDE:INFLATOR MODULE    650
EQUIPMENT                                          648
EQUIPMENT ADAPTIVE/MOBILITY                        439
AIR BAGS:FRONTAL:DRIVER SIDE:INFLATOR MODULE       406
ELECTRICAL SYSTEM                                  229
AIR BAGS:FRONTAL                                   222
LATCHES/LOCKS/LINKAGES                             186
EQUIPMENT:OTHER:LABELS                             177
EQUIPMENT:RECREATIONAL VEHICLE/TRAILER             135
SEATS                                              134
Name: count, dtype: int64

In [32]:
df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2025)].value_counts('COMPNAME').head(10)

COMPNAME
BACK OVER PREVENTION:DISPLAY FUNCTION                                                                               2460
ELECTRICAL SYSTEM: INSTRUMENT CLUSTER/PANEL                                                                         1365
ELECTRICAL SYSTEM:SOFTWARE                                                                                           300
SERVICE BRAKES, HYDRAULIC:ANTILOCK/TRACTION CONTROL/ELECTRONIC LIMITED SLIP:CONTROL UNIT/MODULE                      233
BACK OVER PREVENTION:SOFTWARE                                                                                        212
STEERING:LINKAGES:TIE ROD ASSEMBLY                                                                                   185
STEERING                                                                                                             157
ELECTRICAL SYSTEM:PROPULSION SYSTEM:TRACTION BATTERY:MANAGEMENT SYSTEM/ENERGY CONTROL MODULE (BMS/BECM):SOFTWARE     156
ELECTRICAL SYSTEM:WIRING                                                                                             137
EQUIPMENT:OTHER:LABELS                                                                                               104
Name: count, dtype: int64

In [25]:
pd.set_option('display.max_columns', None)
df_connected.head()

,RECORD_ID,CAMPNO,MAKETXT,MODELTXT,YEARTXT,MFGCAMPNO,COMPNAME,MFGNAME,BGMAN,ENDMAN,RCLTYPECD,POTAFF,ODATE,INFLUENCED_BY,MFGTXT,RCDATE,DATEA,RPNO,FMVSS,DESC_DEFECT,CONEQUENCE_DEFECT,CORRECTIVE_ACTION,NOTES,RCL_CMPT_ID,MFR_COMP_NAME,MFR_COMP_DESC,MFR_COMP_PTNO,PARK_IT,PARK_OUTSIDE
0,81716,10V008000,DODGE,GRAND CARAVAN,2006,J38,AIR BAGS:FRONTAL:SENSOR/CONTROL MODULE-INACTIVE,CHRYSLER GROUP LLC,20050119.0,20060405.0,V,308950,20100419.0,ODI,"Chrysler (FCA US, LLC)",20100111,20100111,NaN,NaN,CHRYSLER IS RECALLING CERTAIN MODEL YEAR 2005-...,"IF THE FRONT CRASH SENSORS BECOME INOPERATIVE,...",CHRYSLER WILL REPLACE THE FRONT AIRBAG SENSORS...,CHRYSLER'S CAMPAIGN NUMBER IS J38. CHRYSLER HA...,34617000207915000000258,NaN,NaN,NaN,No,No
1,81717,10V317000,PIERCE,DASH,2006,39-0139830,"SERVICE BRAKES, HYDRAULIC:FOUNDATION COMPONENT...",PIERCE MANUFACTURING,NaN,NaN,V,45,20100701.0,MFR,Pierce Manufacturing,20100708,20100708,NaN,NaN,PIERCE IS RECALLING CERTAIN MODEL YEAR 2006 TH...,"IF THIS INTERFERENCE OCCURS, BRAKING PERFORMAN...",DEALERS WILL INSTALL NEW AUTOMATIC TIRE CHAIN ...,PIERCE SAFETY RECALL NO. 39-0139830. OWNERS MA...,36361000876842000000080,NaN,NaN,NaN,No,No
2,81718,10V317000,PIERCE,DASH,2009,39-0139830,"SERVICE BRAKES, HYDRAULIC:FOUNDATION COMPONENT...",PIERCE MANUFACTURING,NaN,NaN,V,45,20100701.0,MFR,Pierce Manufacturing,20100708,20100708,NaN,NaN,PIERCE IS RECALLING CERTAIN MODEL YEAR 2006 TH...,"IF THIS INTERFERENCE OCCURS, BRAKING PERFORMAN...",DEALERS WILL INSTALL NEW AUTOMATIC TIRE CHAIN ...,PIERCE SAFETY RECALL NO. 39-0139830. OWNERS MA...,36361000734769000000080,NaN,NaN,NaN,No,No
3,81719,10V317000,PIERCE,ARROW XT,2009,39-0139830,"SERVICE BRAKES, HYDRAULIC:FOUNDATION COMPONENT...",PIERCE MANUFACTURING,NaN,NaN,V,45,20100701.0,MFR,Pierce Manufacturing,20100708,20100708,NaN,NaN,PIERCE IS RECALLING CERTAIN MODEL YEAR 2006 TH...,"IF THIS INTERFERENCE OCCURS, BRAKING PERFORMAN...",DEALERS WILL INSTALL NEW AUTOMATIC TIRE CHAIN ...,PIERCE SAFETY RECALL NO. 39-0139830. OWNERS MA...,36361000677768000000080,NaN,NaN,NaN,No,No
4,81720,10V317000,PIERCE,ARROW XT,2008,39-0139830,"SERVICE BRAKES, HYDRAULIC:FOUNDATION COMPONENT...",PIERCE MANUFACTURING,NaN,NaN,V,45,20100701.0,MFR,Pierce Manufacturing,20100708,20100708,NaN,NaN,PIERCE IS RECALLING CERTAIN MODEL YEAR 2006 TH...,"IF THIS INTERFERENCE OCCURS, BRAKING PERFORMAN...",DEALERS WILL INSTALL NEW AUTOMATIC TIRE CHAIN ...,PIERCE SAFETY RECALL NO. 39-0139830. OWNERS MA...,36361000390634000000080,NaN,NaN,NaN,No,No

In [30]:
df_connected.to_csv('Fulldata.csv',index=False)

In [35]:
df_connected.groupby(by='YEARTXT')

In [38]:
df_1999=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']<=1999)]

In [45]:
df_2000=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2000)]
df_2001=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2001)]
df_2002=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2002)]
df_2003=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2003)]
df_2004=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2004)]
df_2005=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2005)]
df_2006=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2006)]
df_2007=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2007)]
df_2008=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2008)]
df_2009=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2009)]
df_2010=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2010)]
df_2011=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2011)]
df_2012=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2012)]
df_2013=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2013)]
df_2014=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2014)]
df_2015=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2015)]
df_2016=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2016)]
df_2017=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2017)]
df_2018=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2018)]
df_2019=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2019)]
df_2020=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2020)]
df_2021=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2021)]
df_2022=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2022)]
df_2023=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2023)]
df_2024=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2024)]
df_2025=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2025)]

In [58]:
df_2025.shape

(9617, 29)

In [51]:
df_1999.to_csv('data1999.csv',index=False)
df_2000.to_csv('data2000.csv',index=False)
df_2001.to_csv('data2001.csv',index=False)
df_2002.to_csv('data2002.csv',index=False)
df_2003.to_csv('data2003.csv',index=False)
df_2004.to_csv('data2004.csv',index=False)
df_2005.to_csv('data2005.csv',index=False)
df_2006.to_csv('data2006.csv',index=False)
df_2007.to_csv('data2007.csv',index=False)
df_2008.to_csv('data2008.csv',index=False)
df_2009.to_csv('data2009.csv',index=False)
df_2010.to_csv('data2010.csv',index=False)
df_2011.to_csv('data2011.csv',index=False)
df_2012.to_csv('data2012.csv',index=False)
df_2013.to_csv('data2013.csv',index=False)
df_2014.to_csv('data2014.csv',index=False)
df_2015.to_csv('data2015.csv',index=False)
df_2016.to_csv('data2016.csv',index=False)
df_2017.to_csv('data2017.csv',index=False)
df_2018.to_csv('data2018.csv',index=False)
df_2019.to_csv('data2019.csv',index=False)
df_2020.to_csv('data2020.csv',index=False)
df_2021.to_csv('data2021.csv',index=False)
df_2022.to_csv('data2022.csv',index=False)
df_2023.to_csv('data2023.csv',index=False)
df_2024.to_csv('data2024.csv',index=False)
df_2025.to_csv('data2025.csv',index=False)

In [59]:
df_2026=df_connected[(df_connected['RCLTYPECD']=="V")&(df_connected['YEARTXT']==2026)]
df_2026.to_csv('data2026.csv',index=False)

In [60]:
df_connected.value_counts('YEARTXT').head(10)

YEARTXT
9999    30695
2020    23142
2021    22593
2019    21460
2018    14733
2022    13465
2023    12972
2017    12457
2024    10663
2025     9619
Name: count, dtype: int64

In [64]:
df_connected[(df_connected['COMPNAME']=="BACK OVER PREVENTION:DISPLAY FUNCTION")&(df_connected['RCLTYPECD']=="V")].value_counts('YEARTXT').head(10)

YEARTXT
2025    2460
2024    2278
2023    1688
2026     630
2022     405
2021     164
2020     142
2019     102
2018      19
2017       1
Name: count, dtype: int64